---
- name: Configure and Install Cluster
  hosts: all
  become: yes

  tasks:
    - include_tasks: nfs-server.yml
    - include_tasks: groups.yml
    - include_tasks: keygen.yml

    - name: Install SLURM
      shell: "cd /vagrant/slurm-rpms && yum --nogpgcheck localinstall * -y"
      
    - name: Configure SLURM
      shell: "cp /vagrant/slurm.conf /etc/slurm/slurm.conf"

    - name: Create slurm spool directory
      file:
        path: /var/spool/slurm
        state: directory
        owner: slurm
        group: slurm
        mode: "0755"

    - name: Create slurm log files
      file:
        path: /var/log/slurmctld.log
        state: touch
        owner: slurm
        group: slurm
        mode: "0644"

    - name: Create slurm accounting log file
      file:
        path: /var/log/slurm_jobacct.log
        state: touch
        owner: slurm
        group: slurm
        mode: "0644"

    - name: Create slurm job completion log file
      file:
        path: /var/log/slurm_jobcomp.log
        state: touch
        owner: slurm
        group: slurm
        mode: "0644"

    - name: Enable slurmctld
      shell: "systemctl enable slurmctld.service"
      notify: Start slurmctld

  handlers:
    - name: Start slurmctld
      service:
        name: slurmctld
        state: started
