---
- hosts: all
  become: yes
  
  tasks:
    - name: Install nfs-utils
      apk:
        name: 
          - nfs-utils
        state: present

    - name: Create a mountable directory if it does not exist
      file:
        path: /home/vagrant/nfs_test
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0775'

    - name: Enable rpcbind nfslock nfs
      service:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - rpcbind
        - rpc.statd
        - nfs
     
    - name: Copy exports file.
      template:
        src: ./ansible/exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644
    
    - name: Start NFS service if it's not running
      service:
        name: nfs
        state: started

    - name: Reload NFS and re-export directories
      shell: /usr/sbin/exportfs -ra
