---
- name: Configure worker node
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name: 
          - openmpi
          - openmpi-devel
        state: present
    
    - include_tasks: nfs-client.yml
    - include_tasks: keysync.yml

    - name: Install SLURM
      shell: "cd /vagrant/slurm-rpms && yum --nogpgcheck localinstall * -y"
      
    - name: Configure SLURM
      shell: "cp /vagrant/slurm.conf /etc/slurm/slurm.conf"
    
    - name: Create slurm spool directory
      file:
        path: /var/spool/slurm
        state: directory
        # owner: slurm
        # group: slurm
        mode: "0755"

    - name: Create slurm slurmd log file
      file:
        path: /var/log/slurmd.log
        state: touch
        # owner: slurm
        # group: slurm
        mode: "0644"    
      notify: Stop firewalld
      notify: Disable firewall
   
    - name: Install NTP
      yum:
        name: ntp
        state: present
      tags: ntp

    - name: Enable NTP at boot
      service:
        name: ntpd
        enabled: yes
      tags: ntp

    - name: Update system time using NTP
      command: ntpdate pool.ntp.org
      tags: ntp

    - name: Start NTP service
      service:
        name: ntpd
        state: started
      tags: ntp
    
    - name: Add OpenMPI bin and lib directories to PATH and LD_LIBRARY_PATH
      lineinfile:
        dest: /home/vagrant/.bashrc
        line: "{{ item }}"
        insertafter: EOF
      loop:
        - 'export PATH=/usr/lib64/openmpi/bin:$PATH'
        - 'export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH'

    - name: Load the new environment settings
      shell: source /home/vagrant/.bashrc
    
    - name: Enable slurmd
      shell: "systemctl enable slurmd.service"
      notify: Start slurmd

  handlers:
    - name: Start slurmd
      service:
        name: slurmd
        state: started
    - name: Stop firewall
      service:
        name: firewalld
        state: stopped
    - name: Disable firewall
      service:
        name: firewalld
        enabled: no

