nodes = [
  { :hostname => "dias", :ip => "10.10.17.113", :ssh_key => "#{Dir.home}/.ssh/id_rsa.pub" },
  { :hostname => "yana", :ip => "10.10.17.112", :ssh_key => "#{Dir.home}/Downloads/id_rsa.pub" },
]

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "controller" do |controller|
    controller.vm.hostname = "controller"
    controller.vm.box = "centos/7"
    controller.vm.network "private_network", ip: "10.10.17.100"
    controller.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = "512"
    end
    controller.vm.provision "ansible" do |ansible|
      ansible.playbook = "controller.yml"
    end
  end

  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "centos/7"
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network "private_network", ip: node[:ip]
      nodeconfig.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus = 1
      end
      nodeconfig.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines(node[:ssh_key]).first.strip
        s.inline = <<-SHELL
        echo "#{ssh_pub_key}" >> /home/vagrant/.ssh/authorized_keys
        sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
        sed -i 's/PubkeyAuthentication no/PubkeyAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd.service
        SHELL
      end
      nodeconfig.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
      end
    end
  end
  
end

