version: '3.7'
services:
  gontainer:
    image: cloud-native-practice-gontainer:latest
    ports: 
      - "8080-8083:8080"
    volumes:
      - ./resources/:/tmp/resources/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gontainer

